version: '3'
services:
  postgresql:
    image: postgres
    container_name: my-postgresql
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
